/**
 * Sample Pockets API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PocketTransaction } from './pocketTransaction';
import { PocketCurrency } from './pocketCurrency';


export interface Pocket { 
    id: string;
    name: string;
    funds?: PocketCurrency;
    goal?: PocketCurrency;
    goalDate?: string;
    transactions?: Array<PocketTransaction>;
}

